title: .
description: . #Molecular biologist turned applied scientist. <br> Former synthetic biologist at Prospect Bio
email:
url: 'https://william.science/'



# the base hostname & protocol for your site, e.g. http://example.com
#github: "https://github.com/mozilla/release-blog"
highlighter: rouge

#Navigation
#navigation:
#- title: About
#   url: /about
#- title: GitHub
#   url: https://github.com/wahorvat
#- title: Kaggle
#   url: https://www.kaggle.com/wahorvat
#- title: LinkedIn
#   url: https://www.linkedin.com/in/williamhorvat/


#github: {
#    "hostname": "github.com",
#     "pages_hostname": "github.io",
#     "api_url": "https://api.github.com",
#     "environment": "dotcom",
#     "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
#     "project_title": "Mozilla Releases",
#     "project_tagline": "A page of posts both automated and manual regarding Mozilla software releases.",
#     "owner_name": "mozilla",
#     "owner_url": "https://github.com/mozilla",
#     "repository_url": "https://github.com/mozilla/release-blog",
#     "repository_nwo": "mozilla/release-blog",
#     "repository_name": "release-blog",
#     "zip_url": "https://github.com/mozilla/release-blog/zipball/gh-pages",
#     "tar_url": "https://github.com/mozilla/release-blog/tarball/gh-pages",
#     "clone_url": "https://github.com/mozilla/release-blog.git",
#     "releases_url": "https://github.com/mozilla/release-blog/releases",
#     "issues_url": "https://github.com/mozilla/release-blog/issues",
#     "wiki_url": "https://github.com/mozilla/release-blog/wiki",
#     "language": null,
#     "is_user_page": false,
#     "is_project_page": true,
#     "show_downloads": true,
#     "url": "release.mozilla.org", // (or the CNAME)
# }

#    "pages_hostname": "github.io",
#    "api_url": "https://api.github.com",
#    "environment": "dotcom",
#    "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
#    "project_title": "Mozilla Releases",
#    "project_tagline": "A page of posts both automated and manual regarding Mozilla software releases.",
##    "owner_name": "mozilla",
#   "owner_url": "https://github.com/mozilla",
#    "repository_url": "https://github.com/mozilla/release-blog",
#    "repository_nwo": "mozilla/release-blog",
#    "repository_name": "release-blog",
#    "zip_url": "https://github.com/mozilla/release-blog/zipball/gh-pages",
#    "tar_url": "https://github.com/mozilla/release-blog/tarball/gh-pages",
#    "clone_url": "https://github.com/mozilla/release-blog.git",
#    "releases_url": "https://github.com/mozilla/release-blog/releases",
#    "issues_url": "https://github.com/mozilla/release-blog/issues",
#    "wiki_url": "https://github.com/mozilla/release-blog/wiki",
#    "language": null,
#    "is_user_page": false,
#    "is_project_page": true,
#    "show_downloads": true,
#    "url": "release.mozilla.org", // (or the CNAME)
#}

authors:
  Prospect Bio:
    display_name: Prospect Bio
    gravatar: 1c26d49ffb62a4106644da39c7e6fb4c
    web: https://angel.co/company/prospectbio
    img: https://william.science/themes/frontierline/img/fallbacks/circuits.png
    twitter:
    github:
  Stem Pharm:
    display_name: Stem Pharm
    gravatar: 84ed8c95500cb33a9a53038bb9e8af0e
    web: https://stempharm.com/
    img: https://william.science/themes/frontierline/img/fallbacks/organoids.png
    twitter:
    github:
  UW-Madison:
    display_name: Smith Group - UW-Madison
    gravatar: 16d4d4a441724e006b342ac12507caef
    web: https://smith.chem.wisc.edu/
    img: https://william.science/themes/frontierline/img/fallbacks/tagged.png
    github:
  Kaggle:
    display_name: Kaggle
    gravatar: 5aa2e382197a147b42d020b6878f8623
    web: https://www.kaggle.com/c/jane-street-market-prediction
    img: https://william.science/themes/frontierline/img/fallbacks/mesh.png
    twitter:
    github:

paginate: 12
excerpt_separator: "<!-- more -->"
